// Writes every lucide icon (and alias) as a static SVG under public/icons, so the app can draw any icon the
// model names without bundling lucide's ~1,900-entry dynamic import map. Also refreshes src/card/iconNames.ts.
import { mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(require.resolve('lucide-react/package.json')), 'dist/esm');
const { default: imports } = await import(pathToFileURL(join(root, 'dynamicIconImports.mjs')).href);

const out = join(process.cwd(), 'public/icons');
await mkdir(out, { recursive: true });

const attrs = (o) => Object.entries(o).filter(([k]) => k !== 'key').map(([k, v]) => ` ${k}="${v}"`).join('');
const names = Object.keys(imports).sort();
await Promise.all(names.map(async (name) => {
  const { __iconData: icon } = await imports[name]();
  const body = icon.node.map(([tag, a]) => `<${tag}${attrs(a)}/>`).join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
  await writeFile(join(out, `${name}.svg`), svg);
}));

await writeFile(
  join(process.cwd(), 'src/card/iconNames.ts'),
  `// Generated by scripts/icons.mjs — every icon in public/icons.\nexport const ICON_NAMES = '${names.join('|')}';\n`,
);
console.log(`icons: ${names.length}`);
