/** Anonymous value-row line. GTM can swap this without hunting through the UI. */
export const VALUE_ROW_TEXT = 'Sign in to save this answer';

export const COPY = {
  continueGoogle: 'Continue with Google',
  save: 'Save',
  saved: 'Saved',
  signIn: 'Sign in',
  later: 'Later',
  p3: '2 free questions left today. Sign in to keep going.',
  p4: '1 free question left today.',
  p5: 'That was your last free question today.',
  p5Link: 'Sign in to keep going',
  s1: 'Sign in to keep asking',
  s2: (limit: number) => `You've used today's ${limit} free questions.`,
  s3: "Sign in with Google and we'll run your question right after.",
  s3b: 'Sign in with Google to keep going today.',
  notNow: 'Not now',
  s6: (reset: string) => `Free questions come back at ${reset} your time.`,
  close: 'Close',
  fine: 'By continuing you agree to the Terms and Privacy Policy.',
  terms: 'Terms',
  privacy: 'Privacy Policy',
  cancelled: 'Sign-in was cancelled.',
  failed: "Sign-in didn't work.",
  tryAgain: 'Try again',
  signedCap: (limit: number) => `You've used today's ${limit} questions. More at midnight UTC.`,
  ipCap: (limit: number) => `This network has hit today's limit of ${limit}. More at midnight UTC.`,
  e1: 'Sign-in was cancelled.',
  e2: "Sign-in didn't work.",
  e4: (limit: number) => `You've used today's ${limit} questions. More at midnight UTC.`,
  saveFail: "Couldn't save. Try again.",
  o1: "You're signed in",
  o2: 'Email me ZO launch updates',
  o3: "Optional. Unsubscribe anytime. We don't sell or share your email.",
  o4: 'Done',
  o5: 'Launch emails',
  signedInAs: (email: string) => `Signed in as ${email}`,
  savedTitle: 'Saved',
  loadMore: 'Load more',
  remove: 'Remove',
  emptySaves: 'No saved answers yet.',
  savedAnswers: 'Saved answers',
  sync: 'Sync history & saves to this account',
  dismiss: 'Dismiss',
  tooBig: 'This answer is too big to save.',
  savesError: "Couldn't load saved answers.",
  openSaveError: "Couldn't open that answer.",
  signOut: 'Sign out',
  account: 'Account',
} as const;
